# Generated by Django 5.1 on 2024-08-30 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='stage',
            field=models.CharField(choices=[(1, 'Pendientes'), (2, 'Haciendo'), (3, 'En revision'), (4, 'Completado')], default=(1, 'Pendientes'), max_length=1),
        ),
    ]
