# Generated by Django 5.1 on 2024-08-30 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='stage',
            field=models.IntegerField(choices=[(1, 'Pendientes'), (2, 'Haciendo'), (3, 'En revision'), (4, 'Completado')], default=1),
        ),
    ]
